# Generated by Django 5.1 on 2024-08-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=50, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=50, null=True)),
                ("employee_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=30, null=True)),
                ("last_name", models.CharField(max_length=30, null=True)),
                ("email", models.EmailField(max_length=254, null=True, unique=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("hire_date", models.DateField(null=True)),
                ("position", models.CharField(max_length=50, null=True)),
                ("department", models.CharField(max_length=50, null=True)),
                (
                    "salary",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
    ]
